### ISSUE TITLE
Re software requirements

### ISSUE THREAD

**Issue by yuuuuu422** [hwuhsi/scoop#2]
**Amazing project!**  It's terrific  if you can add more reverse software sharing~

**Comment by hwuhsi** [comment]
You mean reverse engineering software? I have maintained it in another repository. More tools will be added. But I not sure whether I should merge the two repositories.

**Comment by hwuhsi** [comment]
> **Amazing project!** It's terrific if you can add more reverse software sharing~



> **Amazing project!** It's terrific if you can add more reverse software sharing~

You can pull request if you want to add your own.
